# Generated by Django 5.2.6 on 2025-09-13 18:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='news_views',
        ),
    ]
