# Generated by Django 5.2.6 on 2025-09-21 13:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0003_seller'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Seller',
        ),
    ]
