# Generated by Django 5.2.6 on 2025-09-22 09:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0005_product_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='category',
            field=models.CharField(choices=[('clothing', 'Clothing'), ('footwear', 'Footwear'), ('accessories', 'Accessories')], default='update', max_length=20),
        ),
    ]
